# Generated by Django 3.2.8 on 2021-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genero', models.CharField(max_length=30)),
                ('Contra_Capa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=60)),
                ('Autor', models.CharField(max_length=30)),
                ('Editora', models.CharField(max_length=30)),
                ('Data_Publicacao', models.DateField()),
            ],
        ),
    ]
