# Generated by Django 3.2.8 on 2021-11-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=30)),
                ('editora', models.CharField(max_length=30)),
                ('data_publicacao', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='livros',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='Contra_Capa',
            new_name='contra_capa',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='Genero',
            new_name='genero',
        ),
    ]
